### ISSUE TITLE
Delete TODO.markdown

### ISSUE THREAD

**Issue by rsangole** [KentonWhite/ProjectTemplate#249]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- [ ] bug report 
- [ ] feature request
- [x] Other

***

##### Issue Severity Classification - 

(Check one with "x") : 
- [ ] 1 - Severe
- [ ] 2 - Moderate
- [x] 3 - Low

##### Expected Behavior

All to-dos need to be documented in the 'Project section'

##### Current Behavior

We have an old [TODO.markdown](https://github.com/KentonWhite/ProjectTemplate/blob/master/TODO.markdown) which may have useful information for us still.

##### Steps to do

- [x] Review the old [TODO.markdown](https://github.com/KentonWhite/ProjectTemplate/blob/master/TODO.markdown) file
- [x] Document in this issue which portions of that are still relevant and needed
- [x] Make appropriate cards in "Projects"
- [x] Delete the old todo.markdown file

**Comment by KentonWhite** [comment]
Issues in the TODO are either covered by current activities, fixed, or no longer appropriate.   Making a PR with the remove TODO file now.
